name: OpenCast Bot CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Run every hour
    - cron: "0 * * * *"
  workflow_dispatch:
    # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          OPENAI_API_KEY: sk-test-key-for-testing
          TWITTER_API_KEY: test-twitter-key
          TWITTER_API_SECRET: test-twitter-secret
          TWITTER_ACCESS_TOKEN: test-twitter-token
          TWITTER_ACCESS_TOKEN_SECRET: test-twitter-token-secret
          TELEGRAM_BOT_TOKEN: 123456789:ABCdefGHIjklMNOpqrsTUVwxyz
          TELEGRAM_CHAT_ID: -1001234567890
        run: |
          pytest --cov=bot --cov-report=term-missing --cov-fail-under=90

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run OpenCast Bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_ENABLED: true
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TELEGRAM_ENABLED: true
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DRY_RUN: true
          LOG_LEVEL: DEBUG
        run: |
          echo "🔍 Debug: Checking environment variables..."
          echo "OPENAI_API_KEY length: ${#OPENAI_API_KEY}"
          echo "TWITTER_API_KEY length: ${#TWITTER_API_KEY}"
          echo "TWITTER_API_SECRET length: ${#TWITTER_API_SECRET}"
          echo "TWITTER_ACCESS_TOKEN length: ${#TWITTER_ACCESS_TOKEN}"
          echo "TWITTER_ACCESS_TOKEN_SECRET length: ${#TWITTER_ACCESS_TOKEN_SECRET}"
          echo "TWITTER_BEARER_TOKEN length: ${#TWITTER_BEARER_TOKEN}"
          echo "TELEGRAM_BOT_TOKEN length: ${#TELEGRAM_BOT_TOKEN}"
          echo "TELEGRAM_CHAT_ID length: ${#TELEGRAM_CHAT_ID}"
          echo "🔍 Debug: Validating configuration..."
          python -m bot.cli validate-config || echo "⚠️ Config validation failed"
          echo "🔍 Debug: Running bot (simple version)..."
          timeout 180 python scripts/run_bot_simple.py || echo "⚠️ Bot execution failed or timed out"

      - name: Auto-commit changes
        run: |
          git config --local user.email "bot@opencast.dev"
          git config --local user.name "OpenCast Bot"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "🤖 Auto-update: Generated content $(date '+%Y-%m-%d %H:%M UTC')"
            git push
          else
            echo "No changes to commit"
          fi
